Repository Amigos-Informaticos/Loteria, pull requests merged in 2020-11, with the labels that each got.

#21 Mejoras en la clase TCPSocket
  .idea/.idea.Loteria/.idea/contentModel.xml
  .idea/.idea.Loteria/.idea/indexLayout.xml
  .idea/.idea.Loteria/.idea/workspace.xml
  Assets/Logic/Connection/Command.cs
  Assets/Logic/Connection/Configuration.meta
  Assets/Logic/Connection/Configuration/TCPSocketConfiguration.cs
  Assets/Logic/Connection/TCPSocket.cs
  Assets/Logic/LogicAssembly.asmdef
  Assets/Scenes/Login/Login_Scripts/Login.cs
  Assets/Scenes/MainMenu/MainMenu_Script/MainMenuScript.cs
  Assets/Scenes/SignUp/SignUp.unity
  Assets/Scenes/SignUp/SignUp_Scirpt/SignUp.cs
  Assets/Scenes/SignUp/SignUp_Scripts/SignUp.cs
  Assets/Scenes/SignUp/SignUp_Scripts/SignUp.cs.meta
  Assets/Tests.meta
  Assets/Tests/EmailTest.cs
  Assets/Tests/EmailTest.cs.meta
  Assets/Tests/Tests.asmdef
  Assets/Tests/Tests.asmdef.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#32 Score GUI y avance en el controlador
  .idea/.idea.Loteria/.idea/contentModel.xml
  Assets/Scenes/GlobalScore.meta
  Assets/Scenes/GlobalScore/GlobalScore.unity
  Assets/Scenes/GlobalScore/GlobalScore.unity.meta
  Assets/Scenes/GlobalScore/GlobalScore_Scripts.meta
  Assets/Scenes/GlobalScore/GlobalScore_Scripts/GlobalScores.cs
  Assets/Scenes/GlobalScore/GlobalScore_Scripts/GlobalScores.cs.meta
  Assets/Scenes/GlobalScore/icons8_crown_48px.png
  Assets/Scenes/GlobalScore/icons8_crown_48px.png.meta
  Assets/Scenes/SignUp/SignUp_Scripts/SignUp.cs
Labels: GUI

#46 Reducción de invariables en código
  .idea/.idea.Loteria/.idea/contentModel.xml
  Assets/Logic/Configuration/UserConfiguration.cs
  Assets/Resources/MainConfiguration/MainConfiguration.json
  Assets/Scenes/Party/Scripts/PartyScript.cs
Labels: automerge

#47 Corrimiento de cartas - Party
  .idea/.idea.Loteria/.idea/contentModel.xml
  Assets/Resources/LanguageFiles/Messages.json
  Assets/Scenes/CreateParty/CreateParty.meta
  Assets/Scenes/CreateParty/CreateParty.unity
  Assets/Scenes/CreateParty/CreateParty/CreatePartyScript.cs
  Assets/Scenes/CreateParty/CreateParty/CreatePartyScript.cs.meta
  Assets/Scenes/LetsPlay/LestPlayScript.meta
  Assets/Scenes/LetsPlay/LestPlayScript/LetsPlayScript.cs
  Assets/Scenes/LetsPlay/LestPlayScript/LetsPlayScript.cs.meta
  Assets/Scenes/LetsPlay/LetsPlay.unity
  Assets/Scenes/Party/Party.unity
  Assets/Scenes/Party/Scripts/PartyScript.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: automerge
